export const locations = [
  "Andaman and Nicobar",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const propertyTypes = [
  "House",
  "Apartment",
  "Condo",
  "Townhouse",
  "Duplex",
  "Villa",
  "Bungalow",
  "Cottage",
  "Mansion",
  "Studio Apartment",
  "Farmhouse",
  "Flat",
  "Manor",
  "Log Cabin",
  "Terraced House",
  "Beach House",
  "Treehouse",
  "Cabin",
  "Hut",
  "Floating Home",
  "Carriage House",
  "Ranch",
];

export const amenities = [
  // Basic Amenities
  "Electricity",
  "Water supply",
  "Heating system",
  "Air conditioning",
  "Internet access",
  "Telephone line",

  // Kitchen Amenities
  "Stove/oven",
  "Refrigerator",
  "Microwave",
  "Dishwasher",
  "Kitchen sink",
  "Cabinets and storage space",
  "Kitchen utensils",

  // Bathroom Amenities
  "Toilet",
  "Sink",
  "Shower",
  "Bathtub",
  "Towel racks",
  "Vanity",

  // Bedroom Amenities
  "Bed",
  "Mattress",
  "Wardrobe/closet",
  "Dresser",
  "Nightstands",
  "Lamps",

  // Living Room Amenities
  "Sofa/couch",
  "Coffee table",
  "Television",
  "Entertainment center",
  "Bookshelves",
  "Chairs",
  "Lamps",

  // Outdoor Amenities
  "Patio/balcony",
  "Garden",
  "Swimming pool",
  "Deck",
  "BBQ area",
  "Outdoor furniture",

  // Building Amenities
  "Elevator",
  "Gym/fitness center",
  "Parking space",
  "Laundry facilities",
  "Security system",
  "Common areas",

  // Community Amenities
  "Park/playground",
  "Tennis/basketball courts",
  "Clubhouse",
  "Walking/biking trails",
  "Picnic area",
  "Dog park",

  // Accessibility Amenities
  "Wheelchair accessibility",
  "Elevator/lift",
  "Ramps",
  "Handrails",
  "Accessible parking",

  // Utilities
  "Central heating",
  "Central air conditioning",
  "Washer and dryer hookups",
  "Garbage disposal",
  "Recycling facilities",
];
